ss-server:
  image: easypi/shadowsocks-libev
  ports:
    - "443:8388/tcp"
    - "443:8388/udp"
  environment:
    - SERVER_PORT=8388
    - METHOD=chacha20
    - PASSWORD=unidle-olivia-tulwar-helen-unlimp-bocce-haster
  restart: always

kcptun-server:
  image: vmlinz/kcptun
  ports:
    - "21:38081/udp"
  environment:
    - KEY=canter-urania-seres-les-blame-sonnet-yan
    - LISTEN_PORT=38081
    - TARGET_PORT=8388
    - TARGET_ADDR=ss-server
  links:
    - ss-server
  restart: always

